version: '3.8'

services:
  app:
    image: naaadang/blog-app-v1
    container_name: app1
    restart: always
    env_file:
      - .env
    networks:
      - blog-net
    ports:
      - "8081:8080"


volumes:
  blog_pgdata:

networks:
  blog-net:
    external: true
    name: blog-net

